name: LampHomeKitHelper
options:
  bundleIdPrefix: com.volovely
targets:
  LampHomeKitHelper:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    settings:
      base:
        SUPPORTS_MACCATALYST: "YES"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
        SUPPORTS_IOS_APPS_ON_MAC: "NO"
        TARGETED_DEVICE_FAMILY: "2"
        DEVELOPMENT_TEAM: "3MFN7Y7D69"
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.volovely.lamp-homekit-helper
        INFOPLIST_FILE: Sources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/helper.entitlements
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: "NO"
    frameworks:
      - framework: HomeKit.framework
        weak: false
